### ISSUE TITLE
Get noNetwork error when using alchemyapi json RPC url

### ISSUE THREAD

**Issue by birkses** [keep3r-network/cli#1]
## Expected Behavior

Connect to Ethereum network and ask for keep3r bonding verification. 

## Actual Behavior

[gecos@blackarch 17:55:17 ~/cli]$ yarn start --config config.json --secrets secrets.json
yarn run v1.22.17
$ ts-node src/core.ts --config config.json --secrets secrets.json
? Please confirm the address which will work: 0x8A0D0287B8601C9F46f87B505fBf49560f6748FD yes
{"level":"debug","message":"Verifying keeper status","metadata":{"keeper":"0x8A0D0287B8601C9F46f87B505fBf49560f6748FD","timestamp":"2021-12-18T06:55:34.764Z"}}
{"level":"error","message":"uncaughtException: could not detect network (event=\"noNetwork\", code=NETWORK_ERROR, version=providers/5.5.0)\nError: could not detect network (event=\"noNetwork\", code=NETWORK_ERROR, version=providers/5.5.0)\n    at Logger.makeError (/home/gecos/cli/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)\n    at Logger.throwError (/home/gecos/cli/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)\n    at JsonRpcProvider.<anonymous> (/home/gecos/cli/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:403:23)\n    at step (/home/gecos/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.throw (/home/gecos/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at rejected (/home/gecos/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","metadata":{"date":"Sat Dec 18 2021 17:55:34 GMT+1100 (Australian Eastern Daylight Time)","error":{"code":"NETWORK_ERROR","event":"noNetwork","reason":"could not detect network"},"exception":true,"os":{"loadavg":[5.85,3.08,3.01],"uptime":25031.77},"process":{"argv":["/home/gecos/cli/node_modules/.bin/ts-node","/home/gecos/cli/src/core.ts","--config","config.json","--secrets","secrets.json"],"cwd":"/home/gecos/cli","execPath":"/usr/bin/node","gid":1000,"memoryUsage":{"arrayBuffers":17306150,"external":52489138,"heapTotal":187211776,"heapUsed":156980888,"rss":277987328},"pid":23841,"uid":1000,"version":"v17.1.0"},"stack":"Error: could not detect network (event=\"noNetwork\", code=NETWORK_ERROR, version=providers/5.5.0)\n    at Logger.makeError (/home/gecos/cli/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)\n    at Logger.throwError (/home/gecos/cli/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)\n    at JsonRpcProvider.<anonymous> (/home/gecos/cli/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:403:23)\n    at step (/home/gecos/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.throw (/home/gecos/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at rejected (/home/gecos/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2021-12-18T06:55:34.916Z","trace":[{"column":28,"file":"/home/gecos/cli/node_modules/@ethersproject/logger/src.ts/index.ts","function":"Logger.makeError","line":225,"method":"makeError","native":false},{"column":20,"file":"/home/gecos/cli/node_modules/@ethersproject/logger/src.ts/index.ts","function":"Logger.throwError","line":237,"method":"throwError","native":false},{"column":23,"file":"/home/gecos/cli/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts","function":null,"line":403,"method":null,"native":false},{"column":23,"file":"/home/gecos/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js","function":"step","line":48,"method":null,"native":false},{"column":53,"file":"/home/gecos/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js","function":"Object.throw","line":29,"method":"throw","native":false},{"column":65,"file":"/home/gecos/cli/node_modules/@ethersproject/providers/lib/json-rpc-provider.js","function":"rejected","line":21,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}}
error Command failed with exit code 1.

## Steps to Reproduce the Problem

1. Populate secrets.json with private keys
2. Populate config.json

cat config.json
{
  "txRpc": "https://eth-mainnet.alchemyapi.io/v2/bPPRN_PwDQ2I_KS6XaLUp2S362tNNSle",
  "jobs": [
    {
      "path": "node_modules/@keep3r-network/cli-sample-jobs/dist/mainnet/dca"
    },
    {
      "path": "node_modules/@keep3r-network/cli-sample-jobs/dist/mainnet/harvest-v2"
    },
    {
      "path": "node_modules/@keep3r-network/cli-sample-jobs/dist/mainnet/tend-v2"
    },
    {
      "path": "node_modules/@keep3r-network/cli-sample-jobs/dist/mainnet/tend-v2-2"
    }
  ]
}

3. yarn start --config config.json --secrets secrets.json

## Specifications

- Version: .1
- Platform: .1

**Comment by 0xGorilla** [comment]
Hey there! I believe the problem is happening because by default the `localRpc` points to your `localhost:8545` and you are not running a local light node.

Please refer to the updated steps in https://github.com/keep3r-network/cli/pull/2 and let me know how it goes

**Comment by birkses** [comment]
Worked, thanks!
